export const collectionCopy = {
  ui: {
    projects: "Projects", insights: "Insights", careers: "Careers", all: "All", contact: "Talk to our team",
    projectFilter: "Filter projects by category", tagFilter: "Filter insights by topic", results: "Showing",
    noCategoryTitle: "No published projects in this category.", noCategoryBody: "Choose another category or talk to our team about your requirements.",
    noArticlesTitle: "No articles published yet.", noArticlesBody: "Our editorial drafts are being prepared for review. Published perspectives will appear here when ready.",
    noTagTitle: "No published articles for this topic.", noTagBody: "Try another topic or explore all published insights.",
    projectOverview: "Overview", challenge: "The challenge", scope: "Scope", approach: "Approach", delivered: "Services delivered",
    methodology: "Technology & data methodology", outcomes: "Approved outcomes", relatedServices: "Related services",
    readProject: "Explore project", readArticle: "Read article", readingTime: "min read", published: "Published", updated: "Updated",
    relatedArticles: "Related perspectives", backInsights: "All insights", backProjects: "All projects",
    openRoles: "Open roles", noRoles: "No open positions right now", noRolesBody: "You can still introduce yourself and your area of interest through our contact page.",
    responsibilities: "Responsibilities", requirements: "Requirements", location: "Location", mode: "Work mode", type: "Employment type",
    closingDate: "Closing date", noClosingDate: "Not specified", apply: "Apply", 
    closedTitle: "This role is closed", closedBody: "Applications are no longer being considered for this role. Explore current opportunities or contact us with a general enquiry.",
    roleOverview: "About the role", viewRole: "View role", currentRoles: "Explore open roles",
    draft: "DRAFT — review before launch", legalNotice: "This is a draft template. It must be reviewed by legal counsel and updated to match the implemented data practices before launch.",
    privacy: "Privacy Policy", terms: "Terms", notFoundEyebrow: "404 / Page not found",
    notFoundTitle: "Page not found", notFoundBody: "The page may have moved, may not be published yet, or the address may be incorrect.",
    returnHome: "Return home", exploreServices: "Explore our services", helpfulLinks: "A useful next step",
    notFoundContact: "Need help finding something? Contact our team.",
    whyCareers: "How we aim to work", whyCareersBody: "Clear responsibilities, considered communication and practical collaboration guide our approach to work. Any role-specific terms will be discussed explicitly.",
  },
  projectsHero: { eyebrow: "Our work", title: "Projects, shared with permission.", description: "Explore approved accounts of our work across social impact, procurement, technology and training." },
  insightsHero: { eyebrow: "Ideas & perspectives", title: "Context for the decisions ahead.", description: "Articles on tender understanding, social impact, procurement and capability building, published after editorial review." },
  careersHero: { eyebrow: "Careers at M2K Global", title: "Bring your perspective to the work.", description: "Explore opportunities to contribute to consulting, coordination, technology delivery and capability building." },
  categories: [
    { id: "social-impact", label: "Social Impact", serviceSlugs: ["social-impact"] },
    { id: "tender-procurement", label: "Tender & Procurement", serviceSlugs: ["tender-advisory", "export-readiness"] },
    { id: "technology", label: "Technology", serviceSlugs: ["it-product-delivery"] },
    { id: "training", label: "Training", serviceSlugs: ["language-training", "skill-development"] },
  ],
  careerPrinciples: [
    { title: "Understand the context", description: "Consider the organization, its stakeholders and the purpose behind an engagement." },
    { title: "Work with clarity", description: "Agree responsibilities and communicate progress, dependencies and questions." },
    { title: "Contribute thoughtfully", description: "Bring relevant expertise, listen to others and document what the work teaches us." },
  ],
  workModes: { onsite: "On-site", hybrid: "Hybrid", remote: "Remote" },
  employmentTypes: { "full-time": "Full-time", "part-time": "Part-time", contract: "Contract", internship: "Internship" },
};
