import type { Service } from "../schemas/content.schema.js";
export const services: Service[] = [
  {
    slug: "social-impact", title: "Social Impact", icon: "Handshake",
    summary: "Translate a social objective into a considered programme, with stakeholder context at its centre.",
    overview: "We support organizations in shaping social-impact initiatives, from understanding a local need to defining the programme scope and reviewing its delivery.",
    problems: ["An objective that needs a practical programme structure", "Multiple stakeholders with different priorities", "A need for clearer documentation and review points"],
    offerings: ["Programme scoping and planning", "Stakeholder consultation support", "Implementation coordination", "Monitoring frameworks and reporting support"],
    approach: "Start with the need and the people affected. Agree what the engagement can reasonably address, then establish responsibilities and a review process.",
    deliverySteps: ["Understand the context and stakeholder needs", "Define programme objectives and scope", "Coordinate an agreed implementation plan", "Review progress and document learning"],
    audience: ["Government bodies and PSUs", "Institutions and community programmes", "Businesses planning social initiatives"],
    sections: [], faqIds: ["engagement-start", "social-scope"],
    seo: { title: "Social Impact Consulting | M2K Global", description: "Programme planning, stakeholder coordination and delivery support for social-impact initiatives." },
  },
  {
    slug: "tender-advisory", title: "Tender Advisory", icon: "Landmark",
    summary: "Understand the opportunity, examine the requirements and approach the bid decision with context.",
    overview: "Tender advisory connects opportunity discovery with the work of understanding a notice, checking eligibility and preparing an organized response.",
    problems: ["Tender information spread across notices and documents", "Uncertainty about eligibility or scope", "Limited time to organize documentation and decisions"],
    offerings: ["Tender discovery and relevance review", "Notice and requirement interpretation", "Bid/no-bid decision support", "Documentation planning and expert coordination"],
    approach: "Use the official notice as the source of truth. We help structure the review, identify questions and coordinate guidance around the requirements.",
    deliverySteps: ["Understand the business profile", "Review the opportunity and official documents", "Discuss eligibility, capacity and bid considerations", "Plan documentation and expert guidance"],
    audience: ["MSMEs and growing businesses", "Consulting and service organizations", "Infrastructure and supply businesses"],
    sections: [], faqIds: ["tender-decisions", "official-notice"],
    seo: { title: "Tender Advisory | M2K Global", description: "Support for tender understanding, eligibility review, bid/no-bid decisions and documentation planning." },
  },
  {
    slug: "it-product-delivery", title: "IT & Product Delivery", icon: "Monitor",
    summary: "Turn a business requirement into a coordinated product journey through managed delivery and technology partners.",
    overview: "We deliver products through managed delivery and technology partners. Our role covers understanding requirements, defining scope, coordinating partner delivery and supporting quality review and handover.",
    problems: ["A business idea that needs a clear product brief", "Technical work that needs coordinated ownership", "A need to connect delivery milestones with business priorities"],
    offerings: ["Discovery and requirements definition", "Product scoping and delivery planning", "Technology partner coordination", "Quality review, acceptance and handover support"],
    approach: "Business requirements guide the work. Technology partners provide specialist implementation, while the engagement sets clear responsibilities, milestones and review points.",
    deliverySteps: ["Discover the problem and intended users", "Agree requirements, scope and partner responsibilities", "Coordinate delivery and review milestones", "Support acceptance, documentation and handover"],
    audience: ["Government bodies and institutions", "Businesses and MSMEs", "Organizations developing digital products"],
    sections: [], faqIds: ["technology-delivery", "technology-ownership"],
    seo: { title: "Managed IT & Product Delivery | M2K Global", description: "Product discovery, scoping, partner coordination and delivery governance through a managed technology delivery model." },
  },
  {
    slug: "language-training", title: "Language Training", icon: "Languages",
    summary: "Build practical communication skills around the situations your learners encounter.",
    overview: "Language programmes are shaped around learner needs, communication contexts and an agreed learning plan, with space for practice and feedback.",
    problems: ["Learning needs that vary across a group", "Difficulty connecting language learning with work situations", "A need for structured practice and feedback"],
    offerings: ["Learner needs assessment", "Workplace communication programmes", "Language practice and guided activities", "Learning reviews and progress feedback"],
    approach: "Start with where learners are and what they need to communicate. Define the programme level, format and learning objectives before delivery.",
    deliverySteps: ["Understand learner needs and context", "Agree learning objectives and format", "Deliver guided practice and feedback", "Review learning and next steps"],
    audience: ["Educational institutions", "Businesses and workplace teams", "Groups preparing for professional communication"],
    sections: [], faqIds: ["training-format", "training-outcomes"],
    seo: { title: "Language Training | M2K Global", description: "Context-led language and workplace communication programmes with structured practice and feedback." },
  },
  {
    slug: "skill-development", title: "Skill Development", icon: "GraduationCap",
    summary: "Shape learning around practical capability, organizational needs and the next step for learners.",
    overview: "We support the planning and coordination of skill-development programmes, linking learning objectives with practical activities and agreed review methods.",
    problems: ["Capability needs without a defined learning pathway", "A gap between training content and practical application", "A need to coordinate programme delivery and review"],
    offerings: ["Training needs and programme scoping", "Employability and workplace skill programmes", "Learning activity and delivery coordination", "Assessment planning and feedback support"],
    approach: "Identify the capabilities the programme should address, consider the learner context and agree how practice and feedback will be built into delivery.",
    deliverySteps: ["Identify capability and learner needs", "Define programme scope and learning objectives", "Coordinate practical learning activities", "Review feedback and further development needs"],
    audience: ["Government and institutional programmes", "Education and training organizations", "Businesses developing workforce capability"],
    sections: [], faqIds: ["training-format", "training-outcomes"],
    seo: { title: "Skill Development | M2K Global", description: "Skill-development programme planning, practical learning and delivery coordination for institutions and businesses." },
  },
  {
    slug: "export-readiness", title: "Export Readiness", icon: "Globe2",
    summary: "Connect with the right domestic and international buyers, organize supplier documents and reach new markets.",
    overview: "We help suppliers prepare to reach new markets by connecting them with relevant buyers, supporting export documentation processes and shaping a practical route to domestic or international opportunities.",
    problems: ["Finding credible domestic or international buyers for your products", "Understanding the documentation needed to approach new markets", "Turning supplier capabilities into relevant business opportunities"],
    offerings: ["Supplier profile and export-readiness review", "Identification of relevant domestic and international buyers", "Buyer–supplier introductions and engagement coordination", "Guidance through export documentation processes", "Market-entry planning aligned with product and business capacity"],
    approach: "We begin with your products, capacity and target markets. Together we clarify the documentation and buyer requirements, then coordinate relevant introductions and next steps. Any market, buyer or regulatory requirements are validated for the specific opportunity.",
    deliverySteps: ["Understand your products, capacity and growth goals", "Review supplier information and documentation readiness", "Identify suitable domestic or international buyer opportunities", "Coordinate introductions and support the next steps"],
    audience: ["Manufacturers, producers and suppliers", "Businesses exploring domestic market expansion", "Indian businesses preparing for international buyer opportunities", "Buyers seeking relevant supplier connections"],
    sections: [], faqIds: ["export-buyer-matching", "export-documentation"],
    seo: { title: "Export Readiness & Buyer Connections | M2K Global", description: "Buyer–supplier connections, export documentation support and domestic or international market opportunities for growing suppliers." },
  },
];
