export const siteCopy = {
  ui: {
    skip: "Skip to content", primaryNavigation: "Main navigation", footerNavigation: "Footer navigation",
    openMenu: "Open menu", closeMenu: "Close menu", menuTitle: "Explore", services: "Services",
    talk: "Talk to Our Team", home: "Home", breadcrumb: "Breadcrumb", loading: "Loading",
    learnMore: "Explore service", allServices: "Explore all services", aboutUs: "Get to know us",
    productName: "Tender Saar", exploreProduct: "Explore Tender Saar", viewPricing: "View pricing",
    login: "Login", startFree: "Start Free", exploreApp: "Explore", contactFallback: "Enquire about Tender Saar",
    contactExplore: "Discuss access", contact: "Contact us", ourWork: "Explore our work",
    allInsights: "View all insights", readInsight: "Read insight", readProject: "View project",
    faq: "Frequently asked questions", faqEyebrow: "A little more clarity",
    overview: "Overview", challenges: "Problems we help address", capabilities: "Our capabilities",
    approach: "How we approach it", process: "From understanding to delivery", audience: "Who we work with",
    relatedProjects: "Related projects", productExample: "A product example", exploreTenderSaar: "Discover Tender Saar",
    sampleBadge: "SAMPLE DATA", mockupLabel: "Tender Saar illustrative dashboard",
    officialSource: "Visit official source portal", footerNote: "Consulting. Technology. Capability.",
    footerCopyright: "All rights reserved.", footerDisclaimer: "Consulting, technology and capability building.",
    pricingTitle: "Plans to be announced", pricingEyebrow: "Pricing", pricingContact: "Discuss your requirements",
    leadershipName: "Mahesh Raana", leadershipRole: "Founder & CEO · 25 years of experience",
    projectsEmptyTitle: "Our work, shared with permission.",
    projectsEmptyBody: "Project stories will be published here once the details are approved for public sharing.",
    insightsEmptyTitle: "Perspectives are on the way.",
    insightsEmptyBody: "We are preparing articles on procurement, technology delivery and capability building.",
    brandDescriptor: "CONSULTING · TECHNOLOGY · SKILLS",
    workflowLabel: "Tender Saar workflow", industriesLabel: "Sectors we work with",
    discoveryLink: "See the sample workspace", sampleResults: "Illustrative opportunities",
    sampleSearch: "Search sample tenders", samplePlaceholder: "Try infrastructure or training",
    noSampleResults: "No sample tenders match your search.", clearSearch: "Clear search",
    deadline: "Deadline", department: "Department", location: "Location", value: "Estimated value",
    guidance: "Bid / no-bid consideration", sampleSummary: "Summary", sampleNotice: "Illustrative interface only. These are not live tender notices. Source links open the official procurement portal.",
    sampleWorkspace: "Tender workspace", sampleProfile: "Your business profile", sampleProfileValue: "Infrastructure & training",
    sampleNav: "Discover opportunities", sampleSection: "DISCOVER", sampleFilter: "All sample tenders",
    mockupAddress: "Tender Saar / workspace preview", pricingConfirmed: "Explore a plan",
  },
  homeHero: {
    eyebrow: "Purpose-led consulting. Practical delivery.",
    title: "Consulting, Technology & Skills for Sustainable Growth",
    description: "Connecting strategy, procurement and capability building to help public institutions and businesses move forward with clarity.",
    primary: { label: "Explore Our Services", href: "/services" },
    secondary: { label: "Talk to Our Team", href: "/contact" },
  },
  aboutHero: {
    eyebrow: "About M2K Global",
    title: "A practical partner for meaningful progress.",
    description: "We bring consulting, technology coordination and learning together around the needs of your organization.",
    primary: { label: "Explore Our Services", href: "/services" },
    secondary: { label: "Start a Conversation", href: "/contact" },
  },
  servicesHero: {
    eyebrow: "Our expertise",
    title: "Connected expertise. A considered approach.",
    description: "From understanding an opportunity to building the capability to act on it. Explore six complementary areas of support.",
    primary: { label: "Find Your Service", href: "#service-areas" },
    secondary: { label: "Discuss Your Requirements", href: "/contact" },
  },
  strip: ["Consulting & advisory", "Tender understanding", "Managed technology delivery", "Training & capability"],
  visualLabels: ["Strategy", "Delivery", "Capability"],
  sections: {
    homeIntro: { eyebrow: "Who we are", title: "Big-picture thinking. Grounded in what comes next.", description: "Progress needs more than a plan. It needs a clear scope, the right people and a practical way forward. We connect advisory support, managed technology delivery and skill development around that idea." },
    services: { eyebrow: "What we do", title: "Expertise that connects the dots.", description: "Six areas of support. One focus: helping your organization take the next informed step." },
    product: { eyebrow: "Introducing Tender Saar", title: "An opportunity is only useful when you understand it.", description: "A focused workspace for tender discovery, understanding and bid/no-bid decision support, with a route to expert guidance." },
    workflow: { eyebrow: "A clearer path", title: "From your business profile to an informed decision.", description: "Bring context to each opportunity before committing time and resources." },
    work: { eyebrow: "Our work", title: "The work behind the words.", description: "A space for approved project stories and practical perspectives on delivery." },
    industries: { eyebrow: "Who we support", title: "Different sectors. Shared ambition.", description: "Our approach starts with your operating context, stakeholders and priorities." },
    why: { eyebrow: "Why work with us", title: "Thoughtful by design. Practical in approach.", description: "The principles that guide how we shape and manage an engagement." },
    insights: { eyebrow: "Ideas & perspectives", title: "A space for informed thinking.", description: "Notes on the decisions, processes and capabilities that help organizations move forward." },
    aboutIntro: { eyebrow: "Our perspective", title: "Strategy, opportunity and capability belong together.", description: "Organizations face decisions that cross disciplines. A procurement opportunity may require a technology solution; a new service may depend on training. Our role is to help connect those needs into a coherent engagement." },
    mission: { eyebrow: "Our mission", title: "Make the next step clearer.", description: "To help organizations understand their needs, define practical responses and coordinate the expertise needed to move forward." },
    vision: { eyebrow: "Our vision", title: "Progress built on capability.", description: "To contribute to institutions and businesses that can make informed decisions, adapt responsibly and develop the skills to sustain their work." },
    values: { eyebrow: "What guides us", title: "Principles with practical meaning.", description: "We aim to make these values visible in the way an engagement is scoped, communicated and delivered." },
    expertise: { eyebrow: "Connected expertise", title: "A wider view of your challenge.", description: "Consulting, tender advisory, technology coordination and training can work together, with clear responsibilities for each part." },
    approach: { eyebrow: "How we work", title: "Start with understanding. Build with purpose.", description: "A structured conversation becomes a shared scope, followed by coordinated delivery and review." },
    leadership: { eyebrow: "Our people", title: "Meet the founder and CEO.", description: "Procurement expertise, strategic advice and practical support for organizations pursuing new opportunities." },
    serviceProduct: { eyebrow: "Product thinking in practice", title: "Introducing Tender Saar.", description: "Tender Saar is a product example within our managed-delivery model, connecting tender discovery, understanding and access to guidance." },
    tenderOverview: { eyebrow: "The idea behind Tender Saar", title: "Less scattered information. More context.", description: "Move from a tender listing to a structured view of the scope, requirements and questions that matter to your business." },
    tenderFeatures: { eyebrow: "Designed around the decision", title: "A clearer view of the opportunity.", description: "Explore the product concept through six connected areas of support." },
    tenderDiscovery: { eyebrow: "Tender discovery", title: "Start with relevance, not just a list.", description: "Use your business profile, sector and location to frame the opportunities worth reviewing. The sample workspace below illustrates that journey." },
    tenderGuidance: { eyebrow: "Understanding & guidance", title: "Know what to examine before you decide.", description: "Review eligibility, scope, timelines and resource commitments. Return to the official notice for complete requirements and seek expert support where needed." },
  },
  pillars: [
    { title: "Context before recommendations", description: "Begin with the organization, its constraints and the people affected by the decision.", icon: "Compass" },
    { title: "Clear scope and ownership", description: "Define responsibilities, dependencies and review points before delivery begins.", icon: "ListChecks" },
    { title: "Connected expertise", description: "Coordinate advisory, technology partners and training around a shared brief.", icon: "Network" },
    { title: "Capability that stays with you", description: "Include knowledge transfer and practical guidance in the delivery approach.", icon: "GraduationCap" },
  ],
  values: [
    { title: "Clarity", description: "Make scope, assumptions and responsibilities understandable.", icon: "ScanLine" },
    { title: "Integrity", description: "Be open about what is known, what needs validation and what is outside scope.", icon: "ShieldCheck" },
    { title: "Collaboration", description: "Work with stakeholders and specialist partners as part of a shared process.", icon: "Handshake" },
    { title: "Practicality", description: "Shape recommendations around the resources and context of the organization.", icon: "Layers" },
  ],
  approach: [
    { title: "Understand", description: "Listen to your objectives, stakeholders and operating context." },
    { title: "Define", description: "Agree the scope, responsibilities and intended deliverables." },
    { title: "Coordinate", description: "Bring the right expertise and technology partners into the process." },
    { title: "Review", description: "Track agreed milestones, gather feedback and support handover." },
  ],
  cta: { eyebrow: "Let's move forward", title: "What would you like to make possible?", description: "Tell us about your priorities. We can start with a conversation about the right approach.", label: "Talk to Our Team", href: "/contact" },
  footerGroups: [
    { title: "Company", links: [{ label: "About us", href: "/about" }, { label: "Careers", href: "/careers" }, { label: "Contact", href: "/contact" }] },
    { title: "Services", links: [{ label: "Social Impact", href: "/services/social-impact" }, { label: "Tender Advisory", href: "/services/tender-advisory" }, { label: "IT & Product Delivery", href: "/services/it-product-delivery" }, { label: "Language Training", href: "/services/language-training" }, { label: "Skill Development", href: "/services/skill-development" }, { label: "Export Readiness", href: "/services/export-readiness" }] },
    { title: "Tender Saar", links: [{ label: "Product overview", href: "/tender-saar" }, { label: "How it works", href: "/tender-saar#how-it-works" }, { label: "Features", href: "/tender-saar#features" }, { label: "Pricing", href: "/tender-saar#pricing" }] },
    { title: "Resources", links: [{ label: "Insights", href: "/insights" }, { label: "Privacy policy", href: "/privacy-policy" }, { label: "Terms", href: "/terms" }] },
  ],
};
